# Generated by Django 4.1.1 on 2022-09-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_remove_student_program_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
