# Generated by Django 4.1.1 on 2022-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=255),
        ),
    ]
