# Generated by Django 4.1.1 on 2022-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_alter_student_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
