# Generated by Django 4.1.1 on 2022-09-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0007_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
